version: '2.1'

services:

  nginx:
    image: nginx:1.13
    depends_on:
      - php
    volumes:
      - ./etc/nginx.global.conf:/etc/nginx/conf.d/global.conf
      - ./etc/nginx.elearning.conf:/etc/nginx/conf.d/elearning.conf
      - ./docroot:/var/www/html/elearning
      - ./repository:/var/www/repository
    env_file:
      - .env

  php:
    image: eaudeweb/php-fpm:7.1-1.0.1
    depends_on:
      - db
    volumes:
      - ./docroot:/var/www/html/elearning
      - ./repository:/var/www/repository

  db:
    image: mariadb:5.5.56
    volumes:
      - ./etc/mysql.server.cnf:/etc/mysql/conf.d/server.cnf
    env_file:
      - .env
      - .env.mysql

  mail:
    image: eeacms/postfix
    hostname: elearning.informea.org
    environment:
      - MTP_HOST=elearning.informea.org
      - MTP_DESTINATION=elearning.informea.org
