version: '2.0'

services:

  nginx:
    container_name: elearn_nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"

  php:
    container_name: elearn_php
    restart: unless-stopped

  db:
    container_name: elearn_db

volumes:
  repository:
    driver: local
