version: '2.0'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
    - php56
    volumes:
      - ./etc/nginx.global.conf:/etc/nginx/conf.d/global.conf
      - ./etc/nginx.elearning.conf:/etc/nginx/conf.d/elearning.conf

  php56:
    image: cristiroma/php-fpm:5.6
    container_name: php56
    depends_on:
    - db

  db:
    image: mariadb
    container_name: db
    volumes:
    - ./etc/mysql.server.cnf:/etc/mysql/conf.d/server.cnf
