version: '2.1'

services:

  nginx:
    container_name: elearn_nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"

  php:
    container_name: elearn_php
    restart: unless-stopped

  db:
    container_name: elearn_db

  mail:
    image: eaudeweb/mailtrap
    container_name: elearn_mailtrap
    restart: unless-stopped
    env_file:
      - .env.mailtrap
    ports:
      - "127.0.0.1:8825:80"
