version: '2.0'

services:

  nginx:
    container_name: elearn_nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"

  php:
    container_name: elearn_php
    restart: unless-stopped

  db:
    container_name: elearn_db

  mail:
    container_name: elearn_db
    image: eaudeweb/mailtrap
    restart: unless-stopped
    container_name: elearn_mailtrap
    env_file:
      - .env.mailtrap
    ports:
      - "127.0.0.1:8825:80"

volumes:
  repository:
    driver: local
