version: '2.0'

services:

  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - ./etc/nginx.global.conf:/etc/nginx/conf.d/global.conf
      - ./etc/nginx.elearning.conf:/etc/nginx/conf.d/elearning.conf

  php:
    image: eaudeweb/php-fpm:7.1-1.0.1
    depends_on:
    - db

  db:
    image: mariadb
    volumes:
    - ./etc/mysql.server.cnf:/etc/mysql/conf.d/server.cnf
